apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansible-slave
  namespace: ansible-cluster
spec:
  replicas: 3  # Create 3 nodes for ansible testing
  selector:
    matchLabels:
      app: ansible-slave
  template:
    metadata:
      labels:
        app: ansible-slave
    spec:
      containers:
      - name: ansible-slave
        image: harshj2003/ansible-slave:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 22
